workflows:
  flutter-workflow:
    name: Flutter Ditonton
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'master'
          include: true
          source: true
    environment:
      groups:
        - FIREBASE
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Skip tests in build since GitHub Actions already runs them
        SKIP_TESTS: true
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    
    scripts:
      - name: Set up Firebase configuration
        script: |
          echo "📱 Setting up Firebase..."
          echo "$ANDROID_FIREBASE_SECRET" | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo "$IOS_FIREBASE_SECRET" | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          
          # Verify
          [ -f "$CM_BUILD_DIR/android/app/google-services.json" ] && echo "✓ Android config ready"
          [ -f "$CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist" ] && echo "✓ iOS config ready"
      
      - name: Get Flutter packages
        script: |
          echo "📦 Getting dependencies..."
          flutter pub get
          
          # Get package dependencies in parallel
          (cd packages/ditonton_core && flutter pub get) &
          (cd packages/ditonton_movies && flutter pub get) &
          (cd packages/ditonton_tv && flutter pub get) &
          wait
          
          echo "✓ All dependencies downloaded"
      
      - name: Run tests
        script: |
          # Skip tests if already run by GitHub Actions
          if [ "${SKIP_TESTS:-false}" = "true" ]; then
            echo "⏭️  Skipping tests (already run by GitHub Actions)"
            exit 0
          fi
          
          echo "🧪 Running tests..."
          cd $CM_BUILD_DIR
          flutter test
          
          cd $CM_BUILD_DIR/packages/ditonton_core && flutter test
          cd $CM_BUILD_DIR/packages/ditonton_movies && flutter test
          cd $CM_BUILD_DIR/packages/ditonton_tv && flutter test
          
          echo "✓ All tests passed"
      
      - name: Build Android APK
        script: |
          echo "🔨 Building release APK..."
          flutter build apk --release \
            --target-platform android-arm,android-arm64 \
            --split-per-abi
          echo "✓ APK built successfully"
      
      - name: Build Android App Bundle
        script: |
          echo "📦 Building App Bundle..."
          flutter build appbundle --release
          echo "✓ AAB built successfully"
      
      # iOS build - uncomment when you have Apple Developer account
      # - name: Build iOS
      #   script: |
      #     echo "🍎 Building iOS..."
      #     flutter build ipa --release \
      #       --export-options-plist=$CM_BUILD_DIR/ios/ExportOptions.plist
      #     echo "✓ iOS built successfully"
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/app-release.aab
      # - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - deltarfd@users.noreply.github.com
        notify:
          success: true
          failure: true
